// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttpvzzhozxcftwfplhnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0cHZ6emhvenhjZnR3ZnBsaG5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMzIzNTQsImV4cCI6MjA1NTgwODM1NH0.7SAOS3ysjGKJ6AnEbKZ8wuBQH3knNDtV94GctDj4lM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);